name: release

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: build webui
        run: |
          npm install
          npm run webui:build
          rm -rf src/web
          rm -rf node_modules
      - name: archive
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'LegacyLoaderQQNT.zip'
          exclusions: '*.zip *.git* CONTRIBUTING.md TODO.md tsconfig.json jsconfig.json vite.config.js'
      - name: generate changelog
        env:
          filename: 'CHANGELOG.md'
        run: |
          echo "## 更新内容:" >> ${{ env.filename }}
          git log --pretty=format:'- %s by @%an' --grep '^(. )?(fix|feat|perf|sync)(\(.+\))?:' -E $(git describe --tags --abbrev=0 ${{ github.ref_name }}^)..${{ github.ref_name }} >> ${{ env.filename }}
          echo -e '\n\n**完整更新日志**: https://github.com/${{ github.repository }}/compare/'$(git describe --tags --abbrev=0 ${{ github.ref_name }}^)'...${{ github.ref_name }}' >> ${{ env.filename }}
          echo '🕘 changelog generated at ${{ env.filename }}'
      - name: release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: 'LegacyLoaderQQNT.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ contains(github.ref_name, 'pre') == false }}
          prerelease: ${{ contains(github.ref_name, 'pre') }}
          name: LegacyLoaderQQNT v${{ github.ref_name }}
          bodyFile: 'CHANGELOG.md'
